"""
Build a calibrated stim DEM from real detection-event data.

Usage
-----
>>> import stim, numpy as np
>>> from build_dem_from_detection_events import build_dem_from_detection_events

# If you have a stim circuit:
>>> circuit = stim.Circuit.from_file("circuit_noisy.stim")
>>> det_data = stim.read_shot_data_file(
...     path="detection_events.b8", format="b8",
...     bit_packed=False, num_detectors=circuit.num_detectors)
>>> dem = build_dem_from_detection_events(circuit, det_data)

# If you only have IBM hardware detection events (no stim circuit):
>>> from build_dem_from_detection_events import build_dem_from_ibm_detection_events
>>> dem = build_dem_from_ibm_detection_events(distance=3, rounds=5, detection_events=det_data)

The graph structure (which detectors each error touches and which logical
observable it flips) is read from the circuit's built-in DEM.  Only the edge
weights are replaced with values estimated from the empirical detection-event
correlations, using the closed-form formulas in Appendix E of
arXiv:2502.17722v1.
"""

import stim
import numpy as np
from typing import Dict, List, Tuple


def build_dem_from_ibm_detection_events(
    distance: int,
    rounds: int,
    detection_events: np.ndarray,
) -> stim.DetectorErrorModel:
    """
    Build a calibrated DEM from IBM hardware detection events, without needing
    a stim circuit.  The graph structure (which detectors each error touches) is
    taken from a standard rotated-memory-Z surface code circuit generated by stim
    for the given distance and number of rounds.  Only the edge weights are
    replaced with values estimated from the empirical detection-event correlations.

    Parameters
    ----------
    distance : int
        Code distance (3, 5, 7, …).
    rounds : int
        Number of syndrome measurement rounds (= T in the circuit).
    detection_events : np.ndarray of shape (n_shots, n_detectors), dtype bool
        One row per shot.  True / 1 means the detector fired.
        The detector ordering must match stim's rotated_memory_z convention for
        the given distance and rounds — use IBMJobDecoder to produce this array.

    Returns
    -------
    stim.DetectorErrorModel
        Calibrated DEM ready for use with pymatching.
    """
    circuit = stim.Circuit.generated(
        "surface_code:rotated_memory_z",
        distance=distance,
        rounds=rounds,
        after_clifford_depolarization=1e-3,  # placeholder; weights are replaced
    )
    return build_dem_from_detection_events(circuit, detection_events)


def build_dem_from_detection_events(
    circuit: stim.Circuit,
    detection_events: np.ndarray,
) -> stim.DetectorErrorModel:
    """
    Build a stim DetectorErrorModel whose edge probabilities are calibrated
    from real detection-event data.

    Parameters
    ----------
    circuit : stim.Circuit
        The stim circuit that generated the detection events.  Its DEM
        provides the graph *structure* — which detectors each error touches
        and which logical observable it flips.  Only the edge weights are
        replaced; no new edges are added.
    detection_events : np.ndarray of shape (n_shots, n_detectors), dtype bool
        One row per shot.  True / 1 means the detector fired (detection event).
        Must match the detector ordering of ``circuit``. (IMPORTANT: if the IBM
        data file uses a different ordering, reorder the columns before calling
        this function!)

    Returns
    -------
    stim.DetectorErrorModel
        A new DEM with the same graph structure as
        ``circuit.detector_error_model()`` but with probabilities estimated
        from the empirical correlations in ``detection_events``.

    Notes
    -----
    The estimation follows Appendix E of arXiv:2502.17722v1.
    Error probabilities are computed in order: 4-body → 3-body → 2-body →
    1-body, each correcting for higher-order contributions.  Error terms with
    computed probability ≤ 1e-15 are omitted from the returned DEM.

    The detector ordering in ``detection_events`` must match the detector
    ordering of ``circuit``. (IMPORTANT: if the IBM data file uses a different
    ordering, reorder the columns before calling this function!)
    """
    data = np.asarray(detection_events, dtype=np.float64)
    if data.ndim != 2:
        raise ValueError("detection_events must be a 2-D array (n_shots, n_detectors)")

    n_shots, n_det = data.shape
    if n_det != circuit.num_detectors:
        raise ValueError(
            f"detection_events has {n_det} columns but circuit has "
            f"{circuit.num_detectors} detectors"
        )

    # Step 1: extract graph structure from the circuit's template DEM
    dem_template = circuit.detector_error_model()
    p_i_keys, p_ij_keys, p_ijk_keys, p_ijkl_keys, all_errors = \
        _extract_dem_structure(dem_template)

    # Step 2: estimate edge probabilities from empirical correlations
    p_i, p_ij, p_ijk, p_ijkl = _compute_probs_from_data(
        data,
        list(p_i_keys),
        list(p_ij_keys),
        list(p_ijk_keys),
        list(p_ijkl_keys),
    )

    # Step 3: assemble and return the calibrated DEM
    return _assemble_dem(all_errors, p_i, p_ij, p_ijk, p_ijkl)


# =============================================================================
# Step 1: parse the template DEM
# =============================================================================

def _extract_dem_structure(
    dem: stim.DetectorErrorModel,
) -> Tuple[Dict, Dict, Dict, Dict, List]:
    """
    Return the sets of error detector-tuples grouped by body count (1–4), plus
    the full list of (det_key, log_mask) pairs needed to rebuild the DEM.
    """
    p_i:    Dict[Tuple[int, ...], float] = {}
    p_ij:   Dict[Tuple[int, ...], float] = {}
    p_ijk:  Dict[Tuple[int, ...], float] = {}
    p_ijkl: Dict[Tuple[int, ...], float] = {}
    all_errors: List[Tuple[Tuple[int, ...], List[int]]] = []

    for instruction in dem:
        if instruction.type != "error":
            continue
        targets = instruction.targets_copy()
        det_key = tuple(sorted(t.val for t in targets if t.is_relative_detector_id()))
        log_ids = [t.val for t in targets if t.is_logical_observable_id()]
        p = instruction.args_copy()[0]

        if   len(det_key) == 1: p_i[det_key]    = p
        elif len(det_key) == 2: p_ij[det_key]   = p
        elif len(det_key) == 3: p_ijk[det_key]  = p
        elif len(det_key) == 4: p_ijkl[det_key] = p

        all_errors.append((det_key, log_ids))

    return p_i, p_ij, p_ijk, p_ijkl, all_errors


# =============================================================================
# Step 2: compute probabilities from correlators (Appendix E of 2502.17722)
# =============================================================================

def _correlator(data: np.ndarray, idxs: Tuple[int, ...], cache: Dict) -> float:
    """
    Multi-body correlator  ⟨∏_i σ̃_i⟩  where  σ̃ = 1 − 2σ  maps {0,1} → {±1}.

    Results are memoised so each unique index tuple is computed only once.
    """
    key = tuple(sorted(idxs))
    if key not in cache:
        vals = 1.0 - 2.0 * data[:, list(key)]   # shape (n_shots, len(key))
        cache[key] = float(np.mean(np.prod(vals, axis=1)))
    return cache[key]


def _p4(i: int, j: int, k: int, l: int,
        data: np.ndarray, cache: Dict) -> float:
    """
    Four-body error probability  p_{ijkl}  — eq. (E4) of arXiv:2502.17722.

      p = 1/2 - 1/2 * (num / den)^{1/8}

    where num and den are products of lower-order correlators.
    Returns 0 if the ratio is negative (unphysical).
    """
    c = _correlator
    num = (c(data, (i,),       cache) * c(data, (j,),       cache) *
           c(data, (k,),       cache) * c(data, (l,),       cache) *
           c(data, (i, j, k),  cache) * c(data, (i, j, l),  cache) *
           c(data, (i, k, l),  cache) * c(data, (j, k, l),  cache))
    den = (c(data, (i, j),     cache) * c(data, (i, k),     cache) *
           c(data, (i, l),     cache) * c(data, (j, k),     cache) *
           c(data, (j, l),     cache) * c(data, (k, l),     cache) *
           c(data, (i, j, k, l), cache))
    if den == 0 or num / den < 0:
        return 0.0
    return 0.5 - 0.5 * (num / den) ** (1.0 / 8)


def _p3(i: int, j: int, k: int,
        data: np.ndarray, cache: Dict,
        p_ijkl_keys: List[Tuple]) -> float:
    """
    Three-body error probability  p_{ijk}  — eq. (E3) of arXiv:2502.17722.

    The four-body correction factor accounts for any four-body error that
    shares all three of {i,j,k}.
    """
    c = _correlator
    num = (c(data, (i,),      cache) * c(data, (j,),      cache) *
           c(data, (k,),      cache) * c(data, (i, j, k), cache))
    den = (c(data, (i, j),    cache) * c(data, (i, k),    cache) *
           c(data, (j, k),    cache))

    correction = 1.0
    for quad in p_ijkl_keys:
        if {i, j, k} <= set(quad):
            (ll,) = set(quad) - {i, j, k}
            v = _p4(i, j, k, ll, data, cache)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)

    if den == 0 or num / den < 0:
        return 0.0
    return 0.5 - 0.5 * (num / den) ** (1.0 / 4) * correction


def _p2(i: int, j: int,
        data: np.ndarray, cache: Dict,
        p_ijk_keys: List[Tuple], p_ijkl_keys: List[Tuple]) -> float:
    """
    Two-body error probability  p_{ij}  — eq. (E2) of arXiv:2502.17722.

    The correction factors subtract contributions from three- and four-body
    errors that share the edge (i,j).
    """
    c = _correlator
    si  = c(data, (i,),    cache)
    sj  = c(data, (j,),    cache)
    sij = c(data, (i, j),  cache)

    if sij == 0 or si * sj / sij < 0:
        return 0.0

    correction = 1.0
    for triple in p_ijk_keys:
        if {i, j} <= set(triple):
            (k,) = set(triple) - {i, j}
            v = _p3(i, j, k, data, cache, p_ijkl_keys)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)
    for quad in p_ijkl_keys:
        if {i, j} <= set(quad):
            k, ll = list(set(quad) - {i, j})
            v = _p4(i, j, k, ll, data, cache)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)

    return 0.5 - 0.5 * np.sqrt(si * sj / sij) * correction


def _p1(i: int,
        data: np.ndarray, cache: Dict,
        p_ij_keys: List[Tuple], p_ijk_keys: List[Tuple],
        p_ijkl_keys: List[Tuple]) -> float:
    """
    Single-body error probability  p_i  — eq. (E1) of arXiv:2502.17722.

    The correction factors subtract contributions from all higher-order errors
    that touch detector i.
    """
    si = _correlator(data, (i,), cache)

    correction = 1.0
    for pair in p_ij_keys:
        if i in pair:
            (j,) = set(pair) - {i}
            v = _p2(i, j, data, cache, p_ijk_keys, p_ijkl_keys)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)
    for triple in p_ijk_keys:
        if i in triple:
            j, k = [x for x in triple if x != i]
            v = _p3(i, j, k, data, cache, p_ijkl_keys)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)
    for quad in p_ijkl_keys:
        if i in quad:
            j, k, ll = [x for x in quad if x != i]
            v = _p4(i, j, k, ll, data, cache)
            if v < 0.5:
                correction /= (1.0 - 2.0 * v)

    return 0.5 - 0.5 * si * correction


def _compute_probs_from_data(
    data: np.ndarray,
    p_i_keys:    List[Tuple],
    p_ij_keys:   List[Tuple],
    p_ijk_keys:  List[Tuple],
    p_ijkl_keys: List[Tuple],
) -> Tuple[Dict, Dict, Dict, Dict]:
    """
    Compute all error probabilities using the Appendix E formulas.

    The computation order matters: 4-body first, then 3-body, 2-body, 1-body.
    Each level uses results from higher levels as correction factors.
    A shared correlator cache avoids redundant sum-over-shots computations.
    """
    cache: Dict = {}

    p_ijkl = {key: _p4(*key, data, cache)
              for key in p_ijkl_keys}

    p_ijk  = {key: _p3(*key, data, cache, p_ijkl_keys)
              for key in p_ijk_keys}

    p_ij   = {key: _p2(*key, data, cache, p_ijk_keys, p_ijkl_keys)
              for key in p_ij_keys}

    p_i    = {key: _p1(key[0], data, cache, p_ij_keys, p_ijk_keys, p_ijkl_keys)
              for key in p_i_keys}

    return p_i, p_ij, p_ijk, p_ijkl


# =============================================================================
# Step 3: assemble the calibrated DEM
# =============================================================================

def _assemble_dem(
    all_errors: List[Tuple[Tuple[int, ...], List[int]]],
    p_i:    Dict,
    p_ij:   Dict,
    p_ijk:  Dict,
    p_ijkl: Dict,
) -> stim.DetectorErrorModel:
    """
    Build a stim DEM by filling in computed probabilities.

    Edges with probability ≤ 1e-15 are dropped; probabilities are clamped
    to [0, 0.5) to stay in the valid stim range.
    """
    lookup = {1: p_i, 2: p_ij, 3: p_ijk, 4: p_ijkl}
    dem = stim.DetectorErrorModel()

    for det_key, log_ids in all_errors:
        prob = float(lookup.get(len(det_key), {}).get(det_key, 0.0))
        prob = max(0.0, min(prob, 0.5 - 1e-10))   # clamp to valid range

        if prob <= 1e-15:
            continue   # skip negligible / zero-weight terms

        targets  = [stim.target_relative_detector_id(d) for d in det_key]
        targets += [stim.target_logical_observable_id(l) for l in log_ids]
        dem.append("error", prob, targets)

    return dem
